package com.example.countdown_timer_app

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents an event entity in the countdown timer app.
 *
 * This class defines the structure of an event, which includes the event's name, date, time,
 * optional notes, and location. The event is stored in a Room database with an auto-generated
 * primary key.
 *
 * @property id The unique identifier for the event, auto-generated by the database.
 * @property eventName The name or title of the event.
 * @property eventDate The date of the event in MM/dd/yyyy format.
 * @property eventTime The time of the event in HH:mm format.
 * @property eventNotes Optional notes associated with the event, can be null.
 * @property eventLocation The location where the event will take place.
 */
@Entity(tableName = "events")
data class Event(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val eventName: String,
    val eventDate: String,
    val eventTime: String,
    val eventNotes: String?,
    val eventLocation: String
)